import React from 'react';

export function LegalPage({ title, content }: { title: string, content: string }) {
  return (
    <div className="min-h-screen bg-[#050505] text-white p-12 md:p-24 selection:bg-blue-500/30">
      <div className="max-w-3xl mx-auto space-y-12">
        <h1 className="text-4xl font-black tracking-tight">{title}</h1>
        <div className="prose prose-invert max-w-none space-y-8 text-white/60 leading-relaxed font-medium">
           {content.split('\n\n').map((p, i) => (
             <p key={i}>{p}</p>
           ))}
        </div>
      </div>
    </div>
  );
}

export const Terms = () => (
  <LegalPage 
    title="Terms of Service" 
    content={`
      Welcome to SiteGenie AI. By using our platform, you agree to the following terms.

      1. Acceptance of Terms: By accessing or using SiteGenie AI, you agree to be bound by these terms. If you do not agree, please do not use the service.

      2. Account Registration: You must provide accurate and complete information when creating an account. You are responsible for all activity under your account.

      3. AI Code Ownership: You retain all rights to the code generated by our AI agents within your workspace. We do not claim ownership of your intellectual property.

      4. Acceptable Use: You may not use SiteGenie AI to build malicious software, engage in illegal activities, or attempt to compromise our infrastructure.

      5. Usage and Limits: We may enforce fair use policies and reasonable protections to preserve performance and stability, but we do not require tokens or subscription billing to access the platform.

      6. Termination: We reserve the right to suspend or terminate accounts that violate our usage policies.
    `}
  />
);

export const Privacy = () => (
  <LegalPage 
    title="Privacy Policy" 
    content={`
      Your privacy is paramount. This policy outlines how we handle your data.

      1. Data Collection: We collect information you provide during registration, as well as usage metadata to improve our AI agents.

      2. Security: We use industry-standard encryption and isolation (Docker) to protect your code and data.

      3. Cookies: We use essential cookies to maintain your session and preferences.

      4. Data Retention: You can delete your projects and account at any time. We retain data only as long as necessary to provide our services.

      5. AI Training: By default, we do not use your private code to train our public models unless you explicitly opt-in to our community data program.
    `}
  />
);
